### ISSUE TITLE
README

### ISSUE THREAD

**Issue by juoceano** [LaPoGeoMar/IntroPython#1]
Todo o texto do README e o nome do ambiente está como o da disciplina de geoquímica, a ideia é não associar de forma alguma a disciplina para não gerar confusão. 
Pensei em um ambiente com o nome do laboratório (LaPoGeo) para facilitar. 

O texto do README eu posso mudar, mas preciso de ajuda para mudar o nome dos ambientes.

**Comment by jojobozz** [comment]
Oi Ju! 
Ainda estou me familiarizando com os comandos, queria confirmar se é assim como está a imagem que deve ficar o ambiente, no caso se assim já estou dentro do ambiente LAPOGEO

![image](https://user-images.githubusercontent.com/68918390/114189815-fe563d80-9920-11eb-8d5d-b196541a63eb.png)

**Comment by juoceano** [comment]
Isso mesmo @jojobozz 
Só para termos certeza, quando puder, reseta o computador e entra no ambiente novamente e me avisa se continuou tudo ok.

**Comment by jojobozz** [comment]
Deu certinho @juoceano :)

**Comment by juoceano** [comment]
Ótimo! As vezes da problema na instalação no Windows depois de resetar.
