### ISSUE TITLE
Exercício_1 

### ISSUE THREAD

**Issue by jojobozz** [LaPoGeoMar/IntroPython#2]
Oi @juoceano, só hoje conseguir mexer no exercício. Tenho tentado abrir o jupyter-notebook, a primeira vez ficou carregando mais de 30 min, aí eu dei um Control+C pra parar tudo... Recomecei as etapas e nessa vez agora já estou há uns 20 minutos esperando e só fica carregando e nada acontece, não sei se pode ser algo que fiz errado ou se é um problema aqui do meu computador. 

![image](https://user-images.githubusercontent.com/68918390/115160777-74b91500-a070-11eb-9d0a-071e5ecf2577.png)

**Comment by ocefpaf** [comment]
Oi @jojobozz. Você tentou clicar link "click here to go to Jupyter"? (Em vermelho na minha figura). Deveria ser automático mas as vezes o Windows não vai. Se mesmo assim não for tenta copiar e colar o URL que tá no terminal e cola no browser (em verde).


![Screenshot_20210418-195924~2](https://user-images.githubusercontent.com/950575/115163558-26ac0d80-a080-11eb-85ae-78b5bc15bf1f.jpg)

**Comment by jojobozz** [comment]
Oi @ocefpaf tentei essas outras formas também, mas o mesmo ocorreu, ficou carregando e nada. Será que o problema é no navegador? Eu uso o microsoft edge como padrão. 
Ainda dei uma olhada nesse tutorial: https://www.dataquest.io/blog/jupyter-notebook-tutorial/ aí fiquei me perguntando se seria melhor fazer a instalação do Anaconda pra conseguir abrir direto o jupyter e criar o notebook, ou se a instalação do jupyter lab no computador, mas não sei como faria pra abrir o notebook atrelada a area do PYTHON_LAPOGEO

**Comment by jojobozz** [comment]
Atualizando: o problema não é o navegador, eu acho. 

Quando tentei abrir o notebook pelo ambiente base ele funcionou, mas pelo ambiente PYTHON_LAPOGEO fica carregando e nada acontece. 

![image](https://user-images.githubusercontent.com/68918390/115166308-eb620c80-a088-11eb-8d4c-f6b849d6f7ec.png)

![image](https://user-images.githubusercontent.com/68918390/115166297-dbe2c380-a088-11eb-8d27-99c2b378e461.png)

**Comment by ocefpaf** [comment]
Não precisa do Anaconda, a sua instalação é o "miniconda" e é praticamente a mesma coisa, só mais "light." Pode ser o navegador sim pq o ambiente carrega um Jupyter com outra configuração diferente do base. Nunca testei no edge. Você tem o Chrome ou Firefox pra testar?

**Comment by jojobozz** [comment]
Fiz o último teste pelo chrome e aconteceu a mesma coisa, fica carregando e não finaliza quando uso o ambiente do PYTHON_LAPOGEO, vou tentar amanhã novamente, e se não der vou tentar refazer as primeiras etapas e recriar o ambiente.

**Comment by ocefpaf** [comment]
Vou testar aqui num laptop Windows e reporto de volta. Mas estranho isso :-/

**Comment by jojobozz** [comment]
Atualização (mais triste do que eu gostaria): Tentei abrir o jupyter depois que o carregamento terminou e acontecia a mesma coisa de ficar carregando a página, ai fiz as etapas que me passou, dei o update e só ficava carregando também a página :( pela base não está abrindo tb, mas acredito que foi porque agora nao fiz a instalação do jupyter 

Quando puder enviar o link com a documentação do WSL, porque não consegui copiar do chat antes de delisgar a chamada, mas to achando que só fazendo pelo Linux mesmo :(

**Comment by ocefpaf** [comment]
Tenta colocar o WSL pra funcionar primeiro: https://docs.microsoft.com/en-us/windows/wsl/install-win10

Depois seria seguir as instruções de Linux. Mas tenho receio que pode ser alguma coisa da firewall do Windows, se for por não funcionar também. Estou lendo sobre isso, mais em breve...

Por enquanto, para poder treinar um pouco, tenta essa instância do mesmo ambiente na nuvem:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/LaPoGeoMar/IntroPython.git/HEAD)

É um pouco lento para abrir e não permite salvar o trabalho mas pelo menos você pode ir começando a treinar um pouco até resolvermos a sua instalação local.

**Comment by ocefpaf** [comment]
Só para testar, de acordo com [essa documentação](https://jupyter-notebook.readthedocs.io/en/stable/troubleshooting.html), as vezes usar `jupyter-notebook` ao invés de `jupyter notebook` "resolve." Acho que vale a pena tentar.

**Comment by jojobozz** [comment]
Oie! Consegui finalmente colocar o Linux no meu computador e agora consigo acessar tranquilamente o jupyter notebook, mas agora o arquivo do exercício 1 não está mais aparecendo aqui no git hub pra eu tentar fazer a atividade.

**Comment by juoceano** [comment]
Que notícia boa Juana! Espero que esteja se adaptando bem ao linux.
Não estou achando o e-mail onde te passei o exercício, então me confirma se foi esse aqui: https://nbviewer.jupyter.org/github/juoceano/2019_MarinePollution/blob/master/aula-01_Comentada.ipynb
Para esse exercício, o arquivo que você precisa é o o "Aula01_BCF.xlsx" que vejo aqui no reposítório do github. No entanto, pode ser que eu esteja enganada e tenha te passado outro exercício.

**Comment by jojobozz** [comment]
Era esse exercício mesmo!! Obrigada Ju!

**Comment by juoceano** [comment]
Achou o arquivo? Se tiver dando algum problema avisa.

**Comment by jojobozz** [comment]
Achei o arquivo sim, está aqui no repositório mesmo. Surgindo dúvidas mando aqui, obrigada!
